### ISSUE TITLE
Helm repo no longer available!

### ISSUE THREAD

**Issue by dongdan39** [apache-spark-on-k8s/kubernetes-HDFS#90]
Hi, 
  Seems your repo is out of date now, please update how to install today, thanks!
[root@kube-1 hdfs]$ helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com
Error: repo "https://kubernetes-charts-incubator.storage.googleapis.com" is no longer available; try "https://charts.helm.sh/incubator" instead

Cheers,
Dan

**Comment by dongdan39** [comment]
More info:

[root@kube-1 hdfs]$ helm repo add incubator https://charts.helm.sh/incubator
"incubator" has been added to your repositories

[root@kube-1 hdfs]$ helm dependency build charts/hdfs-k8s
Error: could not find charts/hdfs-k8s: stat charts/hdfs-k8s: no such file or directory

**Comment by oneslideicywater** [comment]
The stable and incubator repositories of the Helm charts have been moved to a new location. You must updated URI in charts.yaml (or requirements.yaml) to point to the new repositories in order to let the Helm dependency resolver find the correct location.

```bash
Name	Old Location	New Location
stable	https://kubernetes-charts.storage.googleapis.com	https://charts.helm.sh/stable
incubator	https://kubernetes-charts-incubator.storage.googleapis.com	https://charts.helm.sh/incubator
```
you should change the repo of `hdfs-k8s/requirements.yaml` URI.

```yaml
dependencies:
  - name: zookeeper
    version: "1.3.1"
    repository: https://charts.helm.sh/incubator  # change this
    condition: condition.subchart.zookeeper
    tags:
      - ha
      - kerberos

```
